/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "../utils/api";
import { Combobox } from "@headlessui/react";
import { useForm } from "react-hook-form";
import { useEffect, useState } from "react";
type FormInput = {
  venueId: string;
  finalPrice: number;
};

const Home: NextPage = () => {
  const venues = api.cacao.getAllVenues.useQuery();
  const [selectedVenueId, setSelectedVenueId] = useState(venues?.data?.[0]);
  const [query, setQuery] = useState("");
  const form = useForm<FormInput>();
  if (venues.isLoading) return <>Loading!!!...</>;
  const filteredVenues =
    query === ""
      ? venues.data
      : venues.data.filter((venue: { name: string }) => {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          return venue.name?.toLowerCase().includes(query.toLowerCase());
        });

  const handleSelectVenue = (venue: any) => {
    setSelectedVenueId(venue);
  };

  const selectedVenue = venues.data?.find(
    (venue: any) => venue.id === selectedVenueId
  );
  
  console.log("SETTING PRICE !!!: ", selectedVenue?.finalPrice);
  form.setValue("finalPrice", selectedVenue?.finalPrice);
  return (
    <>
      <Head>
        <title>Cacao sub link</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Cacao <span className="text-[hsl(280,100%,70%)]">Sub</span> Link
          </h1>
          <div className="grid grid-cols-1 gap-4">
            <div className="flex max-w-xl flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">Cacao subscriptions</h3>
              <Combobox
                value={selectedVenueId}
                {...form.register("venueId")}
                onChange={handleSelectVenue}
                as="Fragment"
              >
                <Combobox.Input
                  className={"p-2 text-black"}
                  onChange={(event) => setQuery(event?.target?.value)}
                />
                <Combobox.Options>
                  {filteredVenues.map((venue: any) => (
                    <Combobox.Option key={venue.id} value={venue.id}>
                      {venue.name}
                    </Combobox.Option>
                  ))}
                </Combobox.Options>
              </Combobox>
            </div>
            {selectedVenue ? (
              <form>
                <div className="flex max-w-xl flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
                  <h3 className="text-center text-2xl font-bold">
                    {selectedVenue?.name}
                  </h3>
                  <div className="flex items-center gap-3">
                    <p className="text-xl font-bold">Dirección:</p>
                    <p className="text-sm font-bold">
                      {selectedVenue?.address}
                    </p>
                  </div>
                  {selectedVenue.organization.subscription ? (
                    <>
                      <div className="flex items-center gap-3">
                        <p className="text-xl font-bold">
                          Estado de suscripción:
                        </p>
                        <p className="text-sm font-bold">
                          {selectedVenue?.organization?.subscription?.status}
                        </p>
                      </div>
                      <div className="flex items-center gap-3">
                        <p className="text-xl font-bold">Precio:</p>
                        <input
                          type="number"
                          className="w-full rounded-xl border-[2px] border-[#828384] bg-[#f8fafc] p-2.5 text-base font-light !text-black placeholder:text-gray-600"
                          {...form.register("finalPrice")}
                        />
                        <p className="text-sm font-bold">
                          {/* ${selectedVenue?.organization?.subscription?.finalPrice} */}
                        </p>
                      </div>
                      <button
                        type="submit"
                        className="
                        rounded-md bg-indigo-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm 
                        hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 
                        focus-visible:outline-indigo-600
                      "
                      >
                        Actualizar precio
                      </button>
                    </>
                  ) : (
                    <button
                      type="submit"
                      className="
                      rounded-md bg-indigo-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm 
                      hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 
                      focus-visible:outline-indigo-600
                    "
                    >
                      Crear subscripción
                    </button>
                  )}
                </div>
              </form>
            ) : null}
          </div>
          <div className="flex flex-col items-center gap-2">
            {/* <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p> */}
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logeado como {sessionData.user?.name}</span>}
        {/* {secretMessage && <span> - {secretMessage}</span>} */}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
